// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DemoSnippets
{
    internal sealed partial class Vsix
    {
        public const string Id = "DemoSnippets.e2d68c23-8599-40e8-b402-a57060bf3d29";
        public const string Name = "DemoSnippets";
        public const string Description = @"A way to easily add the contents of *.demosnippets files to the Toolbox.";
        public const string Language = "en-US";
        public const string Version = "1.9.6";
        public const string Author = "Matt Lacey";
        public const string Tags = "demo toolbox snippet";
    }
}
